'use client';
import Link from 'next/link';

export default function SSBPersonalInterview() {
  return (
    <div className="min-h-screen bg-surface font-['DM_Sans',sans-serif]">
      <div className="bg-gradient-to-br from-[#1565C0] to-[#0D47A1] text-white py-20 px-6 relative before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-[#FFB300]">
        <div className="max-w-[1080px] mx-auto">
          <Link href="/ssb" className="text-[#E8F2FF] hover:text-white mb-6 inline-block text-sm font-medium transition-colors">
            ← Back to SSB Overview
          </Link>
          <h1 className="font-['Bebas_Neue',sans-serif] text-5xl md:text-7xl mb-4 tracking-wide">SSB Personal Interview</h1>
          <p className="text-xl md:text-2xl text-[#E8F2FF] max-w-2xl font-light">
            One-on-One Assessment of your Character and Awareness
          </p>
        </div>
      </div>

      <div className="max-w-[1080px] mx-auto px-6 py-16 space-y-10 text-[#0D1B2A]">
        <div className="bg-white p-8 rounded-2xl border border-[#C5D8F5] shadow-sm">
          <h2 className="font-['Bebas_Neue',sans-serif] text-3xl text-[#1565C0] tracking-wide mb-4">The Interview Framework</h2>
          <p className="text-[#455A7A] leading-relaxed mb-4">
            The Personal Interview usually lasts between 30 to 60 minutes and is conducted by a senior officer (often the President or Deputy President of the Board). The entire interview revolves around your <strong className="text-[#0D1B2A]">PIQ (Personal Information Questionnaire)</strong> form which you fill out on Day 1.
          </p>
          <p className="text-[#455A7A] leading-relaxed">
            The Interviewing Officer assesses your honesty, clarity of thought, general awareness, and how you handle pressure. They check if the person sitting in front of them matches the psychological profile generated by the Psychologist and GTO.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          <div className="bg-white p-8 rounded-2xl border border-[#C5D8F5] shadow-sm">
            <h2 className="font-['Bebas_Neue',sans-serif] text-3xl text-[#1565C0] tracking-wide mb-6">Common Topics</h2>
            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <span className="w-6 h-6 rounded-full bg-[#E8F2FF] text-[#1565C0] flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">1</span>
                <div>
                  <h4 className="font-bold text-[#0D1B2A]">Family & Background</h4>
                  <p className="text-sm text-[#455A7A]">Relationship with parents/siblings, family income, responsibilities you take at home.</p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-6 h-6 rounded-full bg-[#E8F2FF] text-[#1565C0] flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">2</span>
                <div>
                  <h4 className="font-bold text-[#0D1B2A]">Academics & Sports</h4>
                  <p className="text-sm text-[#455A7A]">Your grades, favorite/least favorite subjects, sports you play, and positions of responsibility held.</p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-6 h-6 rounded-full bg-[#E8F2FF] text-[#1565C0] flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">3</span>
                <div>
                  <h4 className="font-bold text-[#0D1B2A]">Current Affairs</h4>
                  <p className="text-sm text-[#455A7A]">National and international news of the past 6 months, India's foreign relations, and defence updates.</p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <span className="w-6 h-6 rounded-full bg-[#E8F2FF] text-[#1565C0] flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">4</span>
                <div>
                  <h4 className="font-bold text-[#0D1B2A]">Defence Knowledge</h4>
                  <p className="text-sm text-[#455A7A]">Ranks, commands, weapons, and recent acquisitions of the service you are applying for.</p>
                </div>
              </li>
            </ul>
          </div>

          <div className="bg-[#E8F2FF] p-8 rounded-2xl border border-[#C5D8F5]">
            <h2 className="font-['Bebas_Neue',sans-serif] text-3xl text-[#1565C0] tracking-wide mb-6">Common Questions</h2>
            <div className="space-y-3 text-sm text-[#0D1B2A] font-medium">
              <div className="bg-white p-3 rounded-lg shadow-sm border border-[#C5D8F5]">"Why do you want to join the Defence Forces?"</div>
              <div className="bg-white p-3 rounded-lg shadow-sm border border-[#C5D8F5]">"What if you are not recommended this time?"</div>
              <div className="bg-white p-3 rounded-lg shadow-sm border border-[#C5D8F5]">"Tell me your 3 strengths and 3 weaknesses."</div>
              <div className="bg-white p-3 rounded-lg shadow-sm border border-[#C5D8F5]">"Who is your role model and why?"</div>
              <div className="bg-white p-3 rounded-lg shadow-sm border border-[#C5D8F5]">"How do you spend your pocket money?"</div>
              <div className="bg-white p-3 rounded-lg shadow-sm border border-[#C5D8F5]">"Tell me about a time you faced a difficult challenge."</div>
            </div>
          </div>
        </div>

        <div className="bg-white p-8 rounded-2xl border border-green-200 shadow-sm border-l-4 border-l-green-500">
          <h3 className="font-bold text-[#0D1B2A] text-lg mb-2">Golden Rule</h3>
          <p className="text-[#455A7A]">
            Never lie in the personal interview. The Interviewing Officer is highly experienced and trained to catch bluffs. If you do not know the answer to a GK question, simply say, "Sorry sir, I do not know the answer to this, but I will find out." Honesty is always respected.
          </p>
        </div>
      </div>
    </div>
  );
}
